//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerArchitect.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItems
    {
        public int ItemId { get; set; }
        public Nullable<int> CartId { get; set; }
        public Nullable<int> CpuId { get; set; }
        public Nullable<int> MotherboardId { get; set; }
        public Nullable<int> CaseId { get; set; }
        public Nullable<int> GPUId { get; set; }
        public Nullable<int> FanId { get; set; }
        public Nullable<int> RAMId { get; set; }
        public Nullable<int> MemoryId { get; set; }
        public Nullable<int> PowerSuppliesId { get; set; }
        public Nullable<int> CpuCount { get; set; }
        public Nullable<int> MotherboardCount { get; set; }
        public Nullable<int> CaseCount { get; set; }
        public Nullable<int> GPUCount { get; set; }
        public Nullable<int> FanCount { get; set; }
        public Nullable<int> RAMCount { get; set; }
        public Nullable<int> MemoryCount { get; set; }
        public Nullable<int> PowerSuppliesCount { get; set; }
    
        public virtual UsersCarts UsersCarts { get; set; }
        public virtual Cases Cases { get; set; }
        public virtual Coolers Coolers { get; set; }
        public virtual CPUS CPUS { get; set; }
        public virtual GPUS GPUS { get; set; }
        public virtual HDDs HDDs { get; set; }
        public virtual Motherboards Motherboards { get; set; }
        public virtual PowerSupplies PowerSupplies { get; set; }
        public virtual RAMS RAMS { get; set; }
    }
}
