//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerArchitect.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cases()
        {
            this.UserConfiguration = new HashSet<UserConfiguration>();
            this.ReadyMadeAssemblies = new HashSet<ReadyMadeAssemblies>();
        }
    
        public int CaseId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public byte[] Preview_Photo { get; set; }
        public Nullable<int> Cases_Count_on_storage { get; set; }
        public Nullable<int> Seller_Warranty { get; set; }
        public Nullable<int> Country_of_Origin { get; set; }
        public string Model { get; set; }
        public Nullable<int> Manufacturer_Id { get; set; }
        public Nullable<int> Case_Size { get; set; }
        public string Motherboard_Orientation { get; set; }
        public Nullable<int> Length_mm { get; set; }
        public Nullable<int> Width_mm { get; set; }
        public Nullable<int> Height_mm { get; set; }
        public Nullable<decimal> Weight_kg { get; set; }
        public string Main_Color { get; set; }
        public string Case_Material { get; set; }
        public Nullable<bool> Side_Panel_Window { get; set; }
        public string Window_Material { get; set; }
        public string Front_Panel_Material { get; set; }
        public string RGB_Lighting_Type { get; set; }
        public string RGB_Lighting_Color { get; set; }
        public string RGB_Connection_Type { get; set; }
        public string RGB_Control_Method { get; set; }
        public string Compatible_Motherboard_Form_Factors { get; set; }
        public string Compatible_PSU_Form_Factors { get; set; }
        public string PSU_Placement { get; set; }
        public Nullable<int> Max_PSU_Length_mm { get; set; }
        public Nullable<int> Horizontal_Expansion_Slots { get; set; }
        public Nullable<int> Vertical_Expansion_Slots { get; set; }
        public Nullable<int> Max_GPU_Length_mm { get; set; }
        public Nullable<int> Max_CPU_Cooler_Height_mm { get; set; }
        public Nullable<int> Internal_2_5_Drive_Bays { get; set; }
        public Nullable<int> Internal_3_5_Drive_Bays { get; set; }
        public Nullable<int> External_3_5_Drive_Bays { get; set; }
        public Nullable<int> External_5_25_Drive_Bays { get; set; }
        public Nullable<int> Cooling_Fans_Included { get; set; }
        public Nullable<bool> Front_Fan_Support { get; set; }
        public Nullable<bool> Rear_Fan_Support { get; set; }
        public Nullable<bool> Top_Fan_Support { get; set; }
        public Nullable<bool> Bottom_Fan_Support { get; set; }
        public Nullable<bool> Side_Fan_Support { get; set; }
        public Nullable<bool> Liquid_Cooling_Support { get; set; }
        public Nullable<int> Top_Radiator_Size_mm { get; set; }
        public Nullable<int> Rear_Radiator_Size_mm { get; set; }
        public Nullable<int> Bottom_Radiator_Size_mm { get; set; }
        public string Front_Panel_IO_Location { get; set; }
        public string Front_Panel_IO_Ports { get; set; }
        public Nullable<bool> Built_in_PSU { get; set; }
        public Nullable<bool> Low_Noise_Anti_Vibration_Cases { get; set; }
        public string Case_Fixing_Method { get; set; }
        public Nullable<bool> Cable_Management_Holes { get; set; }
        public Nullable<bool> Cable_Cover_Plate { get; set; }
        public Nullable<bool> Dust_Filter { get; set; }
        public string Additional_Features { get; set; }
        public string Included_Accessories { get; set; }
    
        public virtual CaseSizes CaseSizes { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Сountries Сountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserConfiguration> UserConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadyMadeAssemblies> ReadyMadeAssemblies { get; set; }
    }
}
