//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerArchitect.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputerArchitectDataBaseEntities : DbContext
    {
        public ComputerArchitectDataBaseEntities()
            : base("name=ComputerArchitectDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Сountries> Сountries { get; set; }
        public virtual DbSet<CPUS> CPUS { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<Memory_types> Memory_types { get; set; }
        public virtual DbSet<Sockets> Sockets { get; set; }
        public virtual DbSet<Form_Factors> Form_Factors { get; set; }
        public virtual DbSet<Motherboards> Motherboards { get; set; }
        public virtual DbSet<GPUS> GPUS { get; set; }
        public virtual DbSet<RAMS> RAMS { get; set; }
        public virtual DbSet<PowerSupplies> PowerSupplies { get; set; }
        public virtual DbSet<CaseSizes> CaseSizes { get; set; }
        public virtual DbSet<Cases> Cases { get; set; }
        public virtual DbSet<Coolers> Coolers { get; set; }
        public virtual DbSet<SSDs> SSDs { get; set; }
        public virtual DbSet<HDDs> HDDs { get; set; }
        public virtual DbSet<UserConfiguration> UserConfiguration { get; set; }
        public virtual DbSet<ReadyMadeAssemblies> ReadyMadeAssemblies { get; set; }
        public virtual DbSet<CartItems> CartItems { get; set; }
        public virtual DbSet<UsersCarts> UsersCarts { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<OrderCartItems> OrderCartItems { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<DeliveryMethodType> DeliveryMethodType { get; set; }
        public virtual DbSet<PaymentMethodType> PaymentMethodType { get; set; }
        public virtual DbSet<OrderStatuses> OrderStatuses { get; set; }
    }
}
