//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerArchitect.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coolers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coolers()
        {
            this.UserConfiguration = new HashSet<UserConfiguration>();
            this.ReadyMadeAssemblies = new HashSet<ReadyMadeAssemblies>();
            this.CartItems = new HashSet<CartItems>();
            this.OrderCartItems = new HashSet<OrderCartItems>();
        }
    
        public int CoolerId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public byte[] Preview_Photo { get; set; }
        public Nullable<int> Cooler_Count_on_storage { get; set; }
        public Nullable<int> Seller_Warranty { get; set; }
        public Nullable<int> Country_of_Origin { get; set; }
        public string Cooler_Type { get; set; }
        public string Model { get; set; }
        public Nullable<int> Manufacturer_Id { get; set; }
        public Nullable<int> Socket_Type { get; set; }
        public Nullable<int> TDP { get; set; }
        public string Construction_Type { get; set; }
        public string Base_Material { get; set; }
        public string Radiator_Material { get; set; }
        public Nullable<int> Heat_Pipes_Count { get; set; }
        public Nullable<bool> Nickel_Plating { get; set; }
        public string Radiator_Color { get; set; }
        public Nullable<int> Fan_Count { get; set; }
        public Nullable<int> Max_Fan_Count { get; set; }
        public string Fan_Size { get; set; }
        public string Fan_Color { get; set; }
        public string Fan_Connector_Type { get; set; }
        public Nullable<int> Max_Fan_Speed_RPM { get; set; }
        public Nullable<int> Min_Fan_Speed_RPM { get; set; }
        public Nullable<bool> Fan_Speed_Control { get; set; }
        public Nullable<decimal> Max_Airflow_CFM { get; set; }
        public Nullable<decimal> Max_Noise_Level_dB { get; set; }
        public Nullable<decimal> Nominal_Current_Amps { get; set; }
        public Nullable<int> Nominal_Voltage { get; set; }
        public string Bearing_Type { get; set; }
        public Nullable<bool> Thermal_Paste_Included { get; set; }
        public string Lighting_Type { get; set; }
        public string Accessories { get; set; }
        public Nullable<decimal> Height_mm { get; set; }
        public Nullable<decimal> Width_mm { get; set; }
        public Nullable<decimal> Length_mm { get; set; }
        public Nullable<decimal> Weight_g { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Sockets Sockets { get; set; }
        public virtual Сountries Сountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserConfiguration> UserConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadyMadeAssemblies> ReadyMadeAssemblies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItems> CartItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCartItems> OrderCartItems { get; set; }
    }
}
