//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerArchitect.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPUS()
        {
            this.UserConfiguration = new HashSet<UserConfiguration>();
        }
    
        public int CPUId { get; set; }
        public string Product_code { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public byte[] Preview_Photo { get; set; }
        public Nullable<int> CPU_Count_on_storage { get; set; }
        public Nullable<int> Seller_warranty { get; set; }
        public Nullable<int> Country_of_origin { get; set; }
        public string Model { get; set; }
        public Nullable<int> Socket { get; set; }
        public Nullable<int> Manufacturer_Id { get; set; }
        public Nullable<int> Release_year { get; set; }
        public Nullable<bool> Cooling_system_included { get; set; }
        public string Thermal_interface { get; set; }
        public Nullable<int> Total_cores { get; set; }
        public Nullable<int> Productive_cores { get; set; }
        public Nullable<int> Energy_efficient_cores { get; set; }
        public Nullable<int> Max_threads { get; set; }
        public Nullable<decimal> L2_cache_size { get; set; }
        public Nullable<decimal> L3_cache_size { get; set; }
        public Nullable<int> Technology_process { get; set; }
        public string Core { get; set; }
        public Nullable<decimal> Base_processor_speed { get; set; }
        public Nullable<decimal> Max_turbo_speed { get; set; }
        public Nullable<decimal> Base_energy_efficient_speed { get; set; }
        public Nullable<decimal> Turbo_energy_efficient_speed { get; set; }
        public Nullable<bool> Unlocked_multiplier { get; set; }
        public Nullable<int> Memory_type { get; set; }
        public Nullable<int> Max_supported_memory { get; set; }
        public Nullable<int> Number_of_channels { get; set; }
        public Nullable<int> Memory_speed { get; set; }
        public Nullable<bool> ECC_support { get; set; }
        public Nullable<int> Thermal_design_power { get; set; }
        public Nullable<int> Base_thermal_design_power { get; set; }
        public Nullable<decimal> Max_processor_temperature { get; set; }
        public Nullable<bool> Integrated_graphics_core { get; set; }
        public Nullable<int> Integrated_PCI_Express_controller { get; set; }
        public Nullable<int> Number_of_PCI_Express_lines { get; set; }
        public Nullable<bool> Virtualization_technology { get; set; }
        public string Additional_info { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Memory_types Memory_types { get; set; }
        public virtual Sockets Sockets { get; set; }
        public virtual Сountries Сountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserConfiguration> UserConfiguration { get; set; }
    }
}
