//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerArchitect.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GPUS()
        {
            this.UserConfiguration = new HashSet<UserConfiguration>();
            this.ReadyMadeAssemblies = new HashSet<ReadyMadeAssemblies>();
            this.ReadyMadeAssemblies1 = new HashSet<ReadyMadeAssemblies>();
        }
    
        public int GPUId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public byte[] Preview_Photo { get; set; }
        public Nullable<int> GPU_Count_on_storage { get; set; }
        public string GPU_Model { get; set; }
        public Nullable<int> Seller_Warranty { get; set; }
        public Nullable<int> Country_of_Origin { get; set; }
        public Nullable<int> Manufacturer_Id { get; set; }
        public string Color { get; set; }
        public Nullable<bool> Mining_Purpose { get; set; }
        public Nullable<bool> LHR { get; set; }
        public string GPU_Processor { get; set; }
        public string Microarchitecture { get; set; }
        public Nullable<int> Technology_Process_nm { get; set; }
        public Nullable<int> GPU_Base_Frequency_MHz { get; set; }
        public Nullable<int> ALU_Count { get; set; }
        public Nullable<int> Texture_Block_Count { get; set; }
        public Nullable<int> Rasterization_Block_Count { get; set; }
        public Nullable<bool> Ray_Tracing_Support { get; set; }
        public Nullable<int> RT_Cores { get; set; }
        public Nullable<bool> Tensor_Cores { get; set; }
        public Nullable<int> Video_Memory_Size_GB { get; set; }
        public string Video_Memory_Type { get; set; }
        public Nullable<int> Memory_Bus_Width_Bits { get; set; }
        public Nullable<decimal> Memory_Bandwidth_GBps { get; set; }
        public Nullable<int> Memory_Frequency_MHz { get; set; }
        public string Video_Output_Type_and_Count { get; set; }
        public string HDMI_Version { get; set; }
        public Nullable<int> Max_Monitors_Supported { get; set; }
        public string Max_Resolution { get; set; }
        public string Connection_Interface { get; set; }
        public string Connector_Form_Factor { get; set; }
        public Nullable<int> PCI_Express_Lanes { get; set; }
        public Nullable<bool> Additional_Power_Connectors { get; set; }
        public Nullable<int> Recommended_Power_Supply_Watt { get; set; }
        public string Cooling_Type { get; set; }
        public string Fan_Type_and_Count { get; set; }
        public Nullable<bool> Liquid_Cooling_Radiator { get; set; }
        public Nullable<bool> RGB_Lighting { get; set; }
        public Nullable<bool> RGB_Sync { get; set; }
        public Nullable<bool> LCD_Display { get; set; }
        public Nullable<bool> BIOS_Switch { get; set; }
        public Nullable<bool> Low_Profile { get; set; }
        public Nullable<int> Occupied_Expansion_Slots { get; set; }
        public Nullable<int> Length_mm { get; set; }
        public Nullable<int> Width_mm { get; set; }
        public Nullable<int> Thickness_mm { get; set; }
        public Nullable<int> Weight_g { get; set; }
        public Nullable<int> Using_Power_Watt { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Сountries Сountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserConfiguration> UserConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadyMadeAssemblies> ReadyMadeAssemblies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadyMadeAssemblies> ReadyMadeAssemblies1 { get; set; }
    }
}
