//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerArchitect.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDDs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDDs()
        {
            this.UserConfiguration = new HashSet<UserConfiguration>();
            this.ReadyMadeAssemblies = new HashSet<ReadyMadeAssemblies>();
            this.CartItems = new HashSet<CartItems>();
        }
    
        public int HDDId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public byte[] Preview_Photo { get; set; }
        public Nullable<int> HDD_Count_on_storage { get; set; }
        public Nullable<int> Seller_Warranty { get; set; }
        public Nullable<int> Country_of_Origin { get; set; }
        public string HDD_Type { get; set; }
        public string Model { get; set; }
        public Nullable<int> Manufacturer_Id { get; set; }
        public Nullable<int> Capacity_TB { get; set; }
        public Nullable<int> Cache_MB { get; set; }
        public Nullable<int> Spindle_Speed_RPM { get; set; }
        public Nullable<int> Max_Data_Transfer_Speed_MBs { get; set; }
        public Nullable<decimal> Average_Latency_ms { get; set; }
        public string Interface { get; set; }
        public Nullable<decimal> Interface_Bandwidth_GBps { get; set; }
        public Nullable<bool> RAID_Optimization { get; set; }
        public string Recording_Technology { get; set; }
        public Nullable<int> Operational_Shock_Grating_G { get; set; }
        public Nullable<int> Operating_Noise_Level_dBA { get; set; }
        public Nullable<int> Idle_Noise_Level_dBA { get; set; }
        public Nullable<bool> Helium_Filling { get; set; }
        public Nullable<int> Positioning_Parking_Cycles { get; set; }
        public Nullable<decimal> Max_Power_Consumption_Watts { get; set; }
        public Nullable<decimal> Idle_Power_Consumption_Watts { get; set; }
        public Nullable<int> Max_Operating_Temperature_Celsius { get; set; }
        public Nullable<decimal> Width_mm { get; set; }
        public Nullable<decimal> Length_mm { get; set; }
        public Nullable<decimal> Thickness_mm { get; set; }
        public Nullable<decimal> Weight_g { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Сountries Сountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserConfiguration> UserConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadyMadeAssemblies> ReadyMadeAssemblies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItems> CartItems { get; set; }
    }
}
