//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerArchitect.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motherboards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motherboards()
        {
            this.UserConfiguration = new HashSet<UserConfiguration>();
            this.ReadyMadeAssemblies = new HashSet<ReadyMadeAssemblies>();
        }
    
        public int MotherboardId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public byte[] Preview_Photo { get; set; }
        public Nullable<int> Motherboard_Count_on_storage { get; set; }
        public string Motherboard_Model { get; set; }
        public Nullable<int> Seller_warranty { get; set; }
        public Nullable<int> Country_of_Origin { get; set; }
        public Nullable<int> Form_Factor { get; set; }
        public Nullable<int> Height_Mm { get; set; }
        public Nullable<int> Width_Mm { get; set; }
        public Nullable<int> Socket { get; set; }
        public string Chipset { get; set; }
        public string Compatible_Cpu_Cores { get; set; }
        public Nullable<int> Memory_Type { get; set; }
        public string Memory_Form_Factor { get; set; }
        public Nullable<int> Memory_Slots { get; set; }
        public Nullable<int> Memory_Channels { get; set; }
        public Nullable<int> Max_Memory_Gb { get; set; }
        public Nullable<int> Max_Memory_Frequency_Mhz { get; set; }
        public string Pcie_Version { get; set; }
        public Nullable<int> Pcie_X16_Slots { get; set; }
        public Nullable<bool> Sli_Crossfire_Support { get; set; }
        public Nullable<int> Pcie_X1_Slots { get; set; }
        public Nullable<bool> Nvme_Support { get; set; }
        public Nullable<int> M2_Slots { get; set; }
        public Nullable<int> Sata_Ports { get; set; }
        public Nullable<bool> Sata_Raid_Support { get; set; }
        public Nullable<int> Ide_Ports { get; set; }
        public Nullable<int> Rear_Panel_Usb_2_0 { get; set; }
        public Nullable<bool> Rear_Panel_Usb_Type_C { get; set; }
        public Nullable<bool> Rear_Panel_Thunderbolt { get; set; }
        public Nullable<bool> Rear_Panel_Vga { get; set; }
        public Nullable<int> Rear_Panel_Rj45_Ports { get; set; }
        public Nullable<int> Rear_Panel_Analog_Audio_Ports { get; set; }
        public Nullable<bool> Rear_Panel_Spdif { get; set; }
        public Nullable<int> Internal_Usb_2_0 { get; set; }
        public Nullable<bool> Internal_Usb_Type_C { get; set; }
        public Nullable<int> Cpu_Cooler_Power_Pin { get; set; }
        public Nullable<bool> Case_Fan_4_Pin { get; set; }
        public Nullable<int> Case_Fan_3_Pin { get; set; }
        public Nullable<bool> Argb_Lighting { get; set; }
        public Nullable<bool> Rgb_Lighting { get; set; }
        public Nullable<bool> M2_Wifi_Module { get; set; }
        public Nullable<bool> Rs232_Com_Port { get; set; }
        public Nullable<bool> Lpt_Interface { get; set; }
        public string Audio_Scheme { get; set; }
        public string Audio_Chipset { get; set; }
        public Nullable<decimal> Network_Speed_Gbps { get; set; }
        public string Network_Adapter_Brand { get; set; }
        public string Wifi_Standard { get; set; }
        public string Bluetooth_Version { get; set; }
        public string Main_Power_Connector { get; set; }
        public string Cpu_Power_Connector { get; set; }
        public Nullable<int> Power_Phase_Count { get; set; }
        public Nullable<bool> Passive_Chipset_Cooling { get; set; }
        public Nullable<bool> Active_Chipset_Cooling { get; set; }
        public Nullable<bool> Onboard_Buttons { get; set; }
        public Nullable<bool> Lighting_Sync_Software { get; set; }
        public string Bundle_Contents { get; set; }
        public Nullable<decimal> Package_Length_Cm { get; set; }
        public Nullable<decimal> Package_Width_Cm { get; set; }
        public Nullable<decimal> Package_Height_Cm { get; set; }
        public Nullable<decimal> Package_Weight_Kg { get; set; }
    
        public virtual Form_Factors Form_Factors { get; set; }
        public virtual Memory_types Memory_types { get; set; }
        public virtual Sockets Sockets { get; set; }
        public virtual Сountries Сountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserConfiguration> UserConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadyMadeAssemblies> ReadyMadeAssemblies { get; set; }
    }
}
