//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerArchitect.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderCartItems = new HashSet<OrderCartItems>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public Nullable<int> DeliveryMethod { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<System.DateTime> OrderCreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCartItems> OrderCartItems { get; set; }
        public virtual Users Users { get; set; }
        public virtual DeliveryMethodType DeliveryMethodType { get; set; }
        public virtual PaymentMethodType PaymentMethodType { get; set; }
    }
}
