//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerArchitect.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PowerSupplies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PowerSupplies()
        {
            this.UserConfiguration = new HashSet<UserConfiguration>();
        }
    
        public int PowerSupplyId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public byte[] Preview_Photo { get; set; }
        public Nullable<int> Seller_Warranty { get; set; }
        public Nullable<int> Country_of_Origin { get; set; }
        public string Model { get; set; }
        public Nullable<int> Manufacturer_Id { get; set; }
        public Nullable<int> Power_Watt { get; set; }
        public string Form_Factor { get; set; }
        public string Color { get; set; }
        public Nullable<bool> Detachable_Cables { get; set; }
        public Nullable<bool> Cable_Sleeving { get; set; }
        public string Cable_Colors { get; set; }
        public string LED_Type { get; set; }
        public string LED_Color { get; set; }
        public string Main_Power_Connector { get; set; }
        public string CPU_Power_Connector { get; set; }
        public string GPU_Power_Connector { get; set; }
        public Nullable<int> SATA_Connector_Count { get; set; }
        public Nullable<int> Molex_Connector_Count { get; set; }
        public Nullable<bool> Floppy_Connector { get; set; }
        public Nullable<int> Power_12V_Watt { get; set; }
        public Nullable<int> Power_12V1_A { get; set; }
        public Nullable<int> Power_12V2_A { get; set; }
        public Nullable<int> Power_3_3V_A { get; set; }
        public Nullable<int> Power_5V_A { get; set; }
        public Nullable<int> Power_5V_Standby_A { get; set; }
        public Nullable<int> Power_minus12V_A { get; set; }
        public string Input_Voltage_Range { get; set; }
        public string Cooling_System { get; set; }
        public string Fan_Size { get; set; }
        public Nullable<decimal> Max_Noise_Level { get; set; }
        public Nullable<bool> Certification_80PLUS { get; set; }
        public Nullable<bool> Power_Factor_Correction { get; set; }
        public string Standards_Compliance { get; set; }
        public string Protection_Technologies { get; set; }
        public Nullable<int> Length_mm { get; set; }
        public Nullable<int> Width_mm { get; set; }
        public Nullable<int> Height_mm { get; set; }
        public Nullable<decimal> Weight_kg { get; set; }
        public Nullable<int> PS__Count_on_storage { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Сountries Сountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserConfiguration> UserConfiguration { get; set; }
    }
}
