//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerArchitect.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RAMS()
        {
            this.UserConfiguration = new HashSet<UserConfiguration>();
            this.ReadyMadeAssemblies = new HashSet<ReadyMadeAssemblies>();
        }
    
        public int RAMId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public byte[] Preview_Photo { get; set; }
        public Nullable<int> RAM_Count_on_storage { get; set; }
        public string RAM_Model { get; set; }
        public Nullable<int> Seller_Warranty { get; set; }
        public Nullable<int> Country_of_Origin { get; set; }
        public Nullable<int> Manufacturer_Id { get; set; }
        public Nullable<int> Memory_Type { get; set; }
        public string RAM_Form_Factor { get; set; }
        public Nullable<int> Capacity_GB { get; set; }
        public Nullable<bool> Registered_Memory { get; set; }
        public Nullable<bool> ECC_Memory { get; set; }
        public Nullable<int> RAM_Speed_MHz { get; set; }
        public Nullable<bool> AMD_EXPO_Profile { get; set; }
        public Nullable<bool> Intel_XMP_Profile { get; set; }
        public Nullable<int> CAS_Latency { get; set; }
        public Nullable<int> RAS_to_CAS_Delay { get; set; }
        public Nullable<int> Row_Precharge_Delay { get; set; }
        public Nullable<int> Activate_to_Precharge_Delay { get; set; }
        public Nullable<bool> RAM_Heatsink { get; set; }
        public Nullable<bool> RGB_Lighting { get; set; }
        public Nullable<int> RAM_Height_mm { get; set; }
        public Nullable<bool> Low_Profile { get; set; }
        public Nullable<decimal> RAM_Voltage { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Memory_types Memory_types { get; set; }
        public virtual Сountries Сountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserConfiguration> UserConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadyMadeAssemblies> ReadyMadeAssemblies { get; set; }
    }
}
