//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerArchitect.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSDs
    {
        public int SSDId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public byte[] Preview_Photo { get; set; }
        public Nullable<int> SSD_Count_on_storage { get; set; }
        public Nullable<int> Seller_Warranty { get; set; }
        public Nullable<int> Country_of_Origin { get; set; }
        public Nullable<int> SSD_Type { get; set; }
        public string Model { get; set; }
        public Nullable<int> Manufacturer_Id { get; set; }
        public Nullable<int> Volume_GB { get; set; }
        public Nullable<bool> NVMe { get; set; }
        public string Connection_Type { get; set; }
        public Nullable<int> Bits_per_Cell { get; set; }
        public string Memory_Structure { get; set; }
        public Nullable<bool> DRAM_Buffer { get; set; }
        public Nullable<int> Max_Sequential_Read_Speed_MBs { get; set; }
        public Nullable<int> Max_Sequential_Write_Speed_MBs { get; set; }
        public Nullable<decimal> Total_Bytes_Written_TB { get; set; }
        public Nullable<decimal> Drive_Writes_Per_Day { get; set; }
        public Nullable<bool> Hardware_Encryption { get; set; }
        public Nullable<decimal> Width_mm { get; set; }
        public Nullable<decimal> Length_mm { get; set; }
        public Nullable<decimal> Thickness_mm { get; set; }
        public Nullable<decimal> Weight_g { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Сountries Сountries { get; set; }
    }
}
