//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerArchitect.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string PhoneNumber { get; set; }
        public string Password { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string About { get; set; }
        public byte[] Photo { get; set; }
        public string Email { get; set; }
        public int Id { get; set; }
    
        public virtual Сountries Сountries { get; set; }
    }
}
